### ISSUE TITLE
bug(sync): events missing from hubs

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#1045]
**What is the feature you would like to implement?**
We've noticed hubs sometimes miss eth events like fid registrations or name transfers. This causes subsequent valid messages to be dropped and the hub will be always out of sync until it's restarted with `--resync-eth-events`. Hubs should be able to detect this and fix themselves.

A naive approach could be to trigger a full resync if the hubs is out of sync and has fewer events than the other hub. Smarter approach would be to add eth events (and any other dependencies for messages) to the sync trie and determine exactly which blocks were missed and re-try that.

**Why is this feature important?**
Should greatly reduce cases where hubs are permanently out of sync.

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**
A design for the implementation of the feature

**Additional context**

**Comment by adityapk00** [comment]
We're already retrying FID/Registry events during sync

While looking into Issue #1045 (Events should be a part of sync trie), I confirmed that we are, in fact, retrying FID events during sync. The code is in syncEngine::mergeMessages, where we detect if a merge failure is due to
1. Invalid signer, where we attempt to get the signer
2. Invalid FID, where we retry the registry events.

We also have a test to check that this works (MultipeerSyncEngineTest.ts::retry id registry event)

**Comment by varunsrin** [comment]
@CassOnMars 's second change to add eth events to the sync trie which is implemented using a second engine. needs further discussion on backwards compat and how it plugs in

**Comment by varunsrin** [comment]
Looks like resync-eth-events has resulted in hubs converging on a roughly correct state of the network. 

@CassOnMars @adityapk00 and @sanjayprabhu - do we still want to finish the sync trie work? or is that unnecessary complexity at this point?

**Comment by varunsrin** [comment]
deprioritized the ticket for now, will reprioritize closer to the date.

**Comment by adityapk00** [comment]
Discussed with @sanjayprabhu , he'll take this up
