### ISSUE TITLE
bug(hubble): dashboard not working 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1312]
**What is the bug?**
After making a clean install of Hubble, the admin dashboard does not work. It requires navigating to the home page, authenticating with admin/admin and navigating back, which will trip up most users especially since the login seems to fail even when it succeeds. 

**Additional context (optional)**

<img width="953" alt="Screenshot 2023-08-31 at 8 55 37 PM" src="https://github.com/farcasterxyz/hub-monorepo/assets/528882/8ce368f7-515d-4178-8261-4fcfe1b6191a">

**Comment by adityapk00** [comment]
This happens if you've previously logged into a grafana dashboard (from a different instance). Grafana is placing a login cookie in your browser, that's causing it to ask for a password even though the server doesn't need one. 

To get what a normal user is seeing, please either:
1. Open it in a incognito window (where there are no cookies) OR
2. Delete the localhost:3000 cookies

**Comment by varunsrin** [comment]
confirming that clearing cookies worked
