### ISSUE TITLE
bug (replicator): Storage table duplicate entries for each fid

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1397]
**What is the bug?**

<img width="795" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/3dff48a8-f7f2-43fd-ba9a-17b7ba4793ea">

**How can it be reproduced? (optional)**
Run the replicator for a few days

**Comment by zachterrell57** [comment]
+1

**Comment by sds** [comment]
Addressed in the new replicator app in #1462. However, note that it is expected for multiple records for each FID, since each row in the storage table represents a separate `Rent` event. However, there was still a bug in the case reported above with the example replicator app, which is being replaced by the new replicator app.
