### ISSUE TITLE
feat: (replicator) Add column for indexing the root_parent_hash and the root_parent_url for each cast

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1398]
**What is the feature you would like to implement?**
The `casts` table should include:
1. `root_parent_hash` - hash of the root cast. (named threadHash on the warpcast APIs)
2. `root_parent_url` - parent_url of the root cast.

where root cast = parent of the parent of the parent and so on...

Backfill the cast's table for all existing casts.

**Why is this feature important?**
1. A lot of clients have needed this and a hacky version got 7 likes from different developers.

<img width="527" alt="Screenshot 2023-09-19 at 3 15 01 PM" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/dd395817-f041-4c4a-84ab-cff9075b59af">
<img width="489" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/cb51d7bd-7b90-4d71-b864-750635791931">

2. It makes doing analytics around channels much easier

**Will the protocol spec need to be updated??**
No protocol changes needed

**How should this feature be built? (optional)**
Could be implemented via database triggers or can be looked up from the database at insertion time.

**Comment by sds** [comment]
One problem here is that there is no guarantee such information will be available at the time the message is received. Consider casts A → B → C, where "→" denotes "parent of".

If messages A and C are published successfully, there is no way for the replicator to know what the root cast was, since the chain is broken.

What should the behavior be in this case? With Warpcast, we purposely ignore messages referring to a cast that we haven't yet seen, only processing once the referenced cast is published. However, that may not be what others want, and it honestly introduces a fair amount of complexity when determining when to reprocess a message.

We could make the columns nullable and set them on a best-effort basis, so in the case where the chain is broken the row will simply have `root_parent_hash` / `root_parent_url` set to `null`. Then on insertion you need only check your parent's `root_parent_hash` to determine what your `root_parent_hash` should be, etc.

**Comment by manan19** [comment]
Apart from that example, there’s other examples that a full chain or root
parent can’t be found. There’s a chance B got pruned because of storage.

I think nullable works for root_cast_hash because for event root cast we
can list itself as the root_cast_hash. A null would represent “parent not
found”

but for root_parent_url it could represent 2 things - the cast was outside
a channel or “parent not found”. Ideally those states are represented
separately in the same column vs. having to rely on the root_parent_hash
column that it was indeed 1 of these 2 cases.

**Comment by manan19** [comment]
> With Warpcast, we purposely ignore messages referring to a cast that we
haven't yet seen, only processing once the referenced cast is published

I like this solution but do the ignored messages get streamed into the
replicator by the hub or are they just dropped forever?

**Comment by sds** [comment]
If we were to implement this in the replicator, there would be a separate `unprocessed_messages` table. The table has a `blocked_on_hash` column (among others) that is used when the corresponding message is finally seen to then pre-process the blocked message.

So the message is stored, just not processed.

**Comment by manan19** [comment]
That makes sense, let’s do that!
