### ISSUE TITLE
feat: (replicator) Index the sign up timestamp for each fid

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1403]
**What is the feature you would like to implement?**
`fids` table should include a timestamp for when it registered to the protocol. 

**Why is this feature important?**
Developers can display that on clients.

**Will the protocol spec need to be updated??**
No

**Comment by sds** [comment]
Note that the first ~19K FIDs will all have close to the same timestamp since they were migrated in bulk when we moved to Optimism Mainnet.

We're not going to do this, but someone who cares enough about these timestamps could potentially look through v1 and v2 of the contracts to look at those registration times and piece together a hard-coded list that the replicator could use to map FID to "actual" signup timestamp.

But we'll fix this so that for new users going forward we'll incorporate the block timestamp of the onchain event corresponding to the registration.

**Comment by manan19** [comment]
Totally makes sense!

**Comment by mattwelter** [comment]
@sds +1 i also would love this, building a fc app right now, would definitely love this info — so are you saying farcaster is not going to include the first 19k users registered timestamps in the protocol moving forward?

**Comment by sds** [comment]
@mattwelter Those users will have a registration timestamp all around roughly the same time: the point at which we migrated to the Optimism Mainnet L2 chain. Hope that clarifies.

**Comment by sds** [comment]
The new replicator app includes the block timestamp of when the FID was registered.
