### ISSUE TITLE
EACCESS: permisssion denied, open '/home/node/app/apps/hubble/.hub/default_id.protobuf'

### ISSUE THREAD

**Issue by dexeis** [farcasterxyz/hub-monorepo#1879]
**What is the bug?**
Permission issue when you are running `docker compose run hubble yarn identity create`
`EACCESS: permisssion denied, open '/home/node/app/apps/hubble/.hub/default_id.protobuf'`

**How can it be reproduced? (optional)**
Clone the project, move to apps/hubble
run `docker compose run hubble yarn identity create`

**Reason**
This folder is owned by root:root

**Temporary Solution**
In project folder
`cd apps/hubble`
`sudo chown -R yourusername:yourusername .hub`

I've seen several casts from people with this problem, so I thought it would be useful to list the bug and its solution here.

**Comment by sds** [comment]
This is a quirk of working with Docker.

If you use our provided script, it'll take care of this for you: 

https://github.com/farcasterxyz/hub-monorepo/blob/1c9f25275ea5f9aa0d0021c8f5935a1b05cda797/scripts/hubble.sh#L342-L346

Otherwise you're on your own, since Hubble isn't guaranteed to be running as a user with the permissions necessary to change the permissions of the directories it uses.
