### ISSUE TITLE
Message Sync %  shows "No data"

### ISSUE THREAD

**Issue by ithmz** [farcasterxyz/hub-monorepo#1904]
I'm running Hubble using Docker on Windows 11 and the Grafana dashboard show "No Data" for Message Sync?

Can somebody help?

Thanks

![Screenshot 2024-04-13 220347](https://github.com/farcasterxyz/hub-monorepo/assets/23276580/105e5139-f9cb-4fe0-9d50-38b8dce9270a)

**Comment by sds** [comment]
You'll get this while the Hubble is downloading an initial snapshot of the network. It can't know how many messages it has in sync until it's created its initial database.

You can disable snapshot syncing by adding the following flags: `--disable-snapshot-sync --catchup-sync-with-snapshot`, but it'll take a _long_ time to sync all messages, which is why we recommend using the snapshot.
