### ISSUE TITLE
Storage keep instantly growing?

### ISSUE THREAD

**Issue by ithmz** [farcasterxyz/hub-monorepo#1938]
How to deal with this issue?

My cloud storage instantly grows? Quite reach 200 GB already

![image](https://github.com/farcasterxyz/hub-monorepo/assets/23276580/898e6b16-d317-47f7-bda3-06a6a66982c0)

**Comment by materkel** [comment]
Storage requirement from https://www.thehubble.xyz/intro/install.html (40GB) also seems outdated... what even are the "official" specs now to run a farcaster hub with hubble? - Been running one for a few months and it keeps running out of storage since ~1-2 weeks on a 80+ GB volume. Likely due to the same issue as op

**Comment by ithmz** [comment]
How to reduce storage usages?
