### ISSUE TITLE
(200 $USDC) castsByParent with `reverse` parameter fails on popular channels

### ISSUE THREAD

**Issue by nicovalencia** [farcasterxyz/hub-monorepo#1982]
_**edit: 200 $USDC bounty posted on [bountybot](https://warpcast.com/~/conversations/0x24d46886d61fd8690842f4eca4e0aed13ee7768a)**_

**What is the bug?**
When using *certain* channels as parent for `castsByParent`, the data lookup errors *only when reverse=1*.

ie.

```
  const resp = await fetch(
    `${API_URL}/v1/castsByParent?pageSize=1&reverse=1&url=https://warpcast.com/~/channel/${channel}`,
    {
      method: "GET",
    }
  );
```

Will succeed on some channels like `bikes` and fail on ones like `degen`.

Error returned is here:

```
{
  code: 2,
  details: 'db.internal_error/could not get message with key: [ ... ]',
  metadata: { errcode: [ null ] }
}
```

https://github.com/farcasterxyz/hub-monorepo/blob/26ced763673da456f74c041ce7084e2813c83720/apps/hubble/src/addon/src/store/message.rs#L312

**How can it be reproduced? (optional)**
Try calling castsbyparent (api or at the rpc level) with url equal to the degen channel for instance, and set reverse to `1`.

**Additional context (optional)**
Perhaps related to channel size?

Ty for taking a look 🙇 🟣

**Comment by nicovalencia** [comment]
👀

**Comment by BenraouaneSoufiane** [comment]
Hello, you're not providing the required parameters for the castsbyparent endpoint, parent it could be castid object includes fid of the channel I think & hash of cast, or provide parenturl string instead castid
refer to this: https://docs.farcaster.xyz/reference/hubble/grpcapi/casts & this: https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-nodejs/docs/Client.md#getcastsbyparent & this: https://docs.farcaster.xyz/developers/guides/querying/fetch-channel-casts
not works with degen because there are no replies to https://degen.tips
I tested it & it works:
![proof](https://github.com/farcasterxyz/hub-monorepo/assets/110255764/a76cd49d-b60c-4864-a577-f61c79277e12)
![proof2](https://github.com/farcasterxyz/hub-monorepo/assets/110255764/f28a0ff3-8b15-4af9-b53e-142e312b9b76)
If you would like to get casts by channel you should use pinata.cloud api refer to this: https://docs.pinata.cloud/farcaster/farcaster-api/endpoint/casts & add channel, reverse parameters
I tested it & it works
![proof3](https://github.com/farcasterxyz/hub-monorepo/assets/110255764/6aadac20-67f7-4804-aea7-214a3389224c)
![proof4](https://github.com/farcasterxyz/hub-monorepo/assets/110255764/a24c39cb-ce3a-4d21-b319-8bbf63302551)
I'm waiting you to pay the bounty: 0xAa6659efc2165d8ff121C616d9F1039EC1781f12 thanks

**Comment by nicovalencia** [comment]
@BenraouaneSoufiane

The error is that the lookup fails with reverse order only on *certain* channels. For example, the following code works:

```
  const channelName = "bikes";
  const parentUrl = `https://warpcast.com/~/channel/${channelName}`;

  const result = await client.getCastsByParent({
    parentUrl,
    pageSize: 2,
    reverse: true,
  });
```

...but when changing the channel to something like `degen` it fails with the error codes above. This should be supported with the hubble hub alone, not requiring external indices like Pinata's. It may be due to size, or perhaps something else, seemingly erroring at the db call when the client is making the query.

**Comment by BenraouaneSoufiane** [comment]
Gooday, thank you for your fast reply, as per my check the degen channel does not have the parentUrl you provided, the right parentUrl for degen is: chain://eip155:7777777/erc721:0x5d6a07d07354f8793d1ca06280c4adf04767ad7e , so it works using only the hubble hub alone, you need to enter the right parentUrl of the channel, to get it use warpcast api & then pass it to the request query

    import { getSSLHubRpcClient, hexStringToBytes } from '@farcaster/hub-nodejs';
    const hubRpcEndpoint = 'nemes.farcaster.xyz:2283';
    const client = getSSLHubRpcClient(hubRpcEndpoint);
    let parentUrl='';
    client.$.waitForReady(Date.now() + 5000, async (e) => {
        if (e) {
            console.error(`Failed to connect to ${hubRpcEndpoint}:`, e);
           process.exit(1);
        } else {
            console.log(`Connected to ${hubRpcEndpoint}`);
            // Get parentUrl for specific channel
            fetch('https://api.warpcast.com/v1/channel?channelId=degen', {method: 'GET'})
            .then(response => response.json())
            .then(async(response) => {      
              parentUrl = response.result.channel.url;
              console.log(parentUrl);
              // Get casts
              const castsResult = await client.getCastsByParent({ parentUrl: parentUrl });

              castsResult.map((casts) => console.log(casts.messages));
              client.close();
           })
           .catch(err => console.error(err));   
       }
    });
![proof-only-nodejshub](https://github.com/farcasterxyz/hub-monorepo/assets/110255764/51f59e6c-9d68-4657-a3b5-2a0c925fa18e)
I'm waiting you to pay: 0xAa6659efc2165d8ff121C616d9F1039EC1781f12 
Best regards

**Comment by nicovalencia** [comment]
@BenraouaneSoufiane brilliant, I wasn't using the correct parentUrl, and didn't see that in the warpcast API. It is interesting that using the channel URL as parentUrl does work for some queries, which is why I ended up lost.

Docs for anyone else looking: https://docs.farcaster.xyz/reference/warpcast/api

Bounty sent: https://basescan.org/tx/0x20b443d955eb1963583be4b6c86643719f1c90729eec44de9890f8117b19236b

**Comment by BenraouaneSoufiane** [comment]
Thanks @nicovalencia , awesome challenge!
