### ISSUE TITLE
Can I get information about the farcaster nodes that are currently running distributed?

### ISSUE THREAD

**Issue by NB3025** [farcasterxyz/hub-monorepo#2008]
Can I get information about the farcaster nodes that are currently running distributed?

And what are the advantages of building a parcaster node (hubble)?
Are there any benefits (like airdrops) that I can receive in the future?

**Comment by sds** [comment]
> Can I get information about the farcaster nodes that are currently running distributed?

This currently isn't something we have available in this project, but you might be able to find something built by someone else!

> And what are the advantages of building a parcaster node (hubble)? 

Largely for local development if you want to contribute changes. Otherwise, we recommend you run using either a hosted service like Neynar or the ready-to-go script: https://www.thehubble.xyz/intro/hubble.html

>Are there any benefits (like airdrops) that I can receive in the future?

There are no plans.
