### ISSUE TITLE
Port 2283 error

### ISSUE THREAD

**Issue by Rrepl-ch** [farcasterxyz/hub-monorepo#2061]
I installed the node, opened ports 2281 2282 2283. but when I start it gives me this error: ![IMG_20240615_162719.jpg](https://github.com/farcasterxyz/hub-monorepo/assets/79473200/10467404-ac5d-4b37-bb4d-5f59028f172f)

On the grafana website I see the connection but there are no gossip connections and no sync attempts.  how can I solve this problem?  I do it on my PC

**Comment by sds** [comment]
Hey @Rrepl-ch, most home networks route your traffic via a NAT gateway. In short: this allows you to make outbound connections, but not receive inbound connections.

In order for hubs to work properly, they need to reachable from a public IP address. There are ways you can set up your home router to expose a specific host+port to the public internet, but it's highly dependent on your router, ISP, etc.

We recommend running a hub on a cloud infrastructure provider (AWS, GCP, etc.) so that you don't need to fiddle with your home network settings. Hope this helps!
