### ISSUE TITLE
feat: refactor methods to return Result<T, Err> when a failure is possible 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#213]
**What is the feature you would like to implement?**

Refactor the codebase to implement error handling using neverthrow's Result in all public method calls that may fail

**Why is this feature important?**

Today, we have inconsistent error handling across our application. Some parts of our codebase use neverthrow’s Result (an Either monad inspired by Rust) extensively, some use it sparingly for public interfaces and some don’t use it at all and just throw. Our goal is to pick a single error handling strategy and use it consistently to make the code easier to reason about.

Hubs  are an eventually consistent system where correctness is paramount. Introducing bugs and errors, especially in parts that deal with consistency, will be very painful to recover from. It is important that people can make and release changes safely. Hubs are also an open source project that will have a few core contributors and a long tail of casual contributors who may be less familiar with the codebase. It is important that the core contributors can audit and safely reviews the changes being proposed. 

Our error handling system must also be ergonomic in Typescript. We chose a flexibly-typed language because it lets us choose between moving quickly and moving safely. Any solution we choose must also reflect that philosophy and not enforce unnecessary rigidity into our system.

We reject the throw-try-catch approach because it introduces invisible side effects. While it is ergonomic to use in javascript and the most common approach it makes method effects hard to understand. This increases the work that reviewers have to put in to keep the codebase safe. 

**Will the protocol spec need to be updated??**

No

**How should this feature be built? (optional)**

We propose using neverthrow’s Result type along with its corresponding [eslint plugin](https://github.com/mdbetancourt/eslint-plugin-neverthrow). If we cannot show that a method call succeeds without throwing an exception, it should return a Result. Methods on the “edge” that call unsafe code or other libraries that use a try-catch approach must wrap all their calls into a Result safely. 

This has the following benefits: 

1. Readers can immediately tell whether a function is safe or unsafe
2. Readers also know the type of error that may get thrown
3. Authors can never accidentally ignore an error. 

As long as reviewers of code enforce that all unsafe calls to external sources are wrapped in Results, code can be changed safely without introducing unhandled exceptions as shown below

```tsx
async read(): Result<string, JSONError> {
    if (succeeded) {
      return new Ok(['hello']);
    }
    return new Ok(response.result);
  }

const readResult = read();

// Handling errors and values separately (option 1)
if(readResult.isOk()) {
  log.info(value);
} else {
   log.warn(`Error`);
}

// Handling errors and values separately (option 2)
result.match(
    (value) => { log.info(value) },
    (err) => { log.warn(err, `Error`) }
);
```

The primary downside is the verbosity which makes the code visually harder to parse as well as more tedious to write. All methods will often have nested type signatures of the form `Promise<Result<T, Err>>` and callers have more code to unpack results. This is partially mitigated by  features like `unwrapOr` and `andThen` which make it easier  to operate on Results without branching logic under certain conditions.   

```tsx
// Handling errors with default cases 
const string = read().map((str) => str.toUpperCase()).unwrapOr('SOMETHING')

// Handling errors by operating on values and passing errors along
const result = read().andThen(doSomething).andThen(doSomething)
return result
```

The secondary downside is the steeper learning curve, especially when it comes to writing ergonomic code. However, we believe these downsides are outweighed by the long term benefits that come from being protected from unhandled exceptions.

**Comment by Raynos** [comment]
The most recent project I had worked at we returned `{ err, value }` from every single async method and never used `throw` or promise rejections. This made error handling consistent and easy to reason about at every single call site, you have to explicitly handle errors which meant error handling is actually done instead of forgetten.

Using a result library with typescript has far better support from the type system, the `const { err, value } = await read()` approach was slightly more ergonomic with less method calls but we had zero assistance from typescript. 

The steeper learning curve was not too hard to deal with, the wrapping of third party libraries that throw / return promise rejections was a pain, and can sometimes be forgotten.

The javascript exception handling model is frustrating for distributed systems and having something in line with rust or golang that has explicit errors at every call site improves the overall quality and observability of the system.

**Comment by pfletcherhill** [comment]
I had initially moved away from neverthrow because of verbosity but these are all good points and I'm happy to try again

**Comment by goksu** [comment]
I have found this pattern to be somewhat too verbose during unit tests, however in general enjoyed the experience and the trust factor it generates for the overall code. Supportive.

**Comment by sds** [comment]
Our experience using the Result pattern on the backend has been pretty positive, but I would encourage the `error` value to always be set to an actual instance of `Error` (with a stack trace) for aiding in debugging. Preferably a subclass of `Error` that has additional bells and whistles.

This makes bubbling up certain kinds of errors easier, especially if you take the time to define your top-level request entrypoints to interpret error responses and return appropriate response codes.

For example, if deep down in some core logic an invalid parameter is provided, you would return something like a `BadRequestError` and then further up your stack you return a response based on that error if the error cannot be gracefully recovered from.

Sharing some code for illustrative purposes only—please don't take as what we should do word-for-word:

```ts
if (argIsInvalid) {
  return err(new BadRequestError(...));
}
```

In any intermediate code, you handle using:
```ts
if (myIntermediateResult.isErr()) return err(myIntermediateResult.error);
```

Then at the top-level handler for your request, you could have something like...
```ts
if (myFinalResult.isErr()) {
  // Even better if you define a helper to convert an error into a response for you, rather than write explicitly.
  return res.send(myFinalResult.error.statusCode).json({ errors: [myFinalResult.error.message] });
}
return res.send(200).json({ result: 'ok' });
```

You can also handle the error explicitly based on type if necessary (though typically you wouldn't need to, some situations require different approaches based on the cause of the error):
```ts
if (myResult.isErr()) {
  // You probably want a helper to make these less verbose to express (inspecting based on class name or similar)
  if (myResult.error instanceof BadRequestError) {
  } else if (myResult.error instanceof ... ) {
    ...
  }
}
```

Here's some boilerplate you might consider writing to enable the above workflow (ensuring a consistent hierarchy of errors whose properties you can rely on existing):

```ts
export class FarcasterError extends Error {
  // We give this a custom property so that we can easily match on it in tests
  // using toMatchObject matcher (`message` is treated specially).
  public readonly errorMessage!: string;

  public readonly causedBy?: Error;

  // Default value, but should be overridden by subclasses.
  public readonly statusCode: number = 500;

  // Assume by default any error is not safe to share with an end-user.
  public readonly presentable: boolean = false;

  // Assume by default any error should be reported to an error reporting service (Sentry, Datadog, etc.)
  // Allowing this to be customize allows you to make your error reporting more fine-grained.
  public readonly report: boolean = true;
}

export class ClientError extends FarcasterError {
  // Default error code if returning an HTTP response
  public readonly statusCode: number = 400;

  // Client errors are safe to show to the client.
  public readonly presentable: boolean = true;
}

export class BadRequestError extends ClientError {
  public readonly statusCode = 400;
}
```

### Downsides

1. You'll never be able to do fully typed errors in JS—all `try` / `catch` statements need to be of the form `catch (e: any) { ... }`, at which point you ensure `e` is an `Error`, and if it isn't you convert it to one.

2. If you have multiple nested calls that each handle errors if `if` / `else`, you lose the "path" your code took to get to that error if you're just returning the underlying error. Its stack trace will show where the original error was created, but it might not be obvious what path your code took to get to that state since the `if` / `else` handling modifies control flow with no paper trail.

3. As Goksu [mentioned](https://github.com/farcasterxyz/hub/issues/213#issuecomment-1304268664), writing tests can be a little annoying since the type checker usually makes you check the `isErr()` status before inspecting a result (you can use `_unsafeUnwrap()`, but that's pretty ugly in code). A workaround I've found is to use `toMatchObject`, for example:
   ```ts
   # Check that the result is a successful result as well as the underlying value we're expecting
   expect(myResult).toMatchObject({ value: { items: [ ... ] } });

   # Check that the result is an error result with the error we're expecting:
   expect(myResult).toMatchObject({ 
     error: {
       errorMessage: 'Message we're expecting',
       statusCode: 404,
     },
   });
   ```
   Another benefit of this is that when either expectation is violated, you get information about everything (as opposed to a binary true/false with no context about the actual value/error).

Not all of these suggestions will make sense in the context of the hub, but as they are based on practical experience with the `Result` pattern at scale, I hope the lessons are at least useful in information the direction we take the hub.

**Comment by Raynos** [comment]
```
  if (myResult.error instanceof BadRequestError) {
```

In a networked program you want to try to normalize to something like `if (myResult.error.type === 'bad-request-error') {` so that you can serialize errors consistently as something like `{ message, type, stack }` and switch on a string field like `type` or `name` or something equivelant. 

Relying on `instanceof` means you have to wrap all inbound errors over the network as `new BadRequestError(message, meta)` when you get a remote error.

Whether that field is called `type` or `name` or `code` or something else is not very relevant. I've tried numerous approaches to structured or wrapper errors like https://github.com/Raynos/error or https://github.com/TritonDataCenter/node-verror but the approach of creating a new error constructor and subclassing a base error works great too.

> If you have multiple nested calls that each handle errors with if / else, you lose the "path" your code took to get to that error if you're just returning the underlying error. Its stack trace will show where the original error was created, but it might not be obvious what path your code took to get to that state since the if / else handling modifies control flow with no paper trail.

If you wrap errors and concatenate stack traces or at least have a linked list of errors and allow a caller to get a shallow or concatenated stack trace then you have the full paper trail. 

When it comes to a networked program we found it useful to ask questions about an `Error` and whether a condition applied,

For example

 - Classify it as a certain label, Protocol, Network, BadRequest, Declined, etc ( https://github.com/uber/tchannel-node/blob/master/errors.js#L653 )
  - Ask if an error is retryable, ask if an error means the remote node is "unhealthy", ask if an error is fatal.
  - Added helpers, like converting an error into a HTTP status code / message
  
 I found the design of tchannel protocol where errors had a human readable message and a machine readable code ( https://github.com/uber/tchannel/blob/master/docs/protocol.md#code1-1 ) to be really useful. What the various `code` fields are is far more specific to the farcaster protocol and would require me to re-read the whole protocol and think more about that.

**Comment by varunsrin** [comment]
Starting to implement the design here: https://github.com/farcasterxyz/hub/pull/226

I recommend not using the [eslint plugin](https://github.com/mdbetancourt/eslint-plugin-neverthrow) because it requires the use of `match` or `unwrapOr` for every result. This doesn't allow us to specify the control flow logic of "return if error encountered, otherwise move execution forward" within a function.  See the example below where the behavior is implement with an isErr() check. 

```ts
  private async demo(): Promise<HubResult<number>> {

    const checkResult = callErrorProneMethod();
    if (checkResult.isErr()) return err(new HubError('unavailable', { cause: checkResult.error }));

    const someValue = doFoo();
    return someValue;
  }
```

There isn't a way to use match (as shown below) since control flow will not return the outer function from the error closure.

```ts
private async demo(): Promise<HubResult<number>> {

  const checkResult = callErrorProneMethod();
  if (checkResult.isErr()) return err(new HubError('unavailable', { cause: checkResult.error }));

  callErrorProneMethod().match(
    () => {
      // no-op
    },
    (e) => {
      // does not return the outer function.
      return err(e);
    }

  const someValue = doFoo();
  return someValue;
}
```

There isn't a way to do this cleanly with `unwrapOr` since that just specifies a default value, which is not very helpful either. 


Rust, which the eslint rule is based on, does not have this problem since it can return from the inner function and also supports the terse `?` operator which makes the syntax much more ergonomic (see: https://doc.rust-lang.org/std/result/#the-question-mark-operator-). But there isn't a similar convenience in typescript making this behavior impractical to implement.

**Comment by varunsrin** [comment]
Implementation Checklist

- [ ] Deprecate all instances of FarcasterError
- [ ] Deprecate all possible instances of try/catch (or leave comments)
- [ ] Deprecate all possible instances of throw (or leave comments) 
- [ ] Replace all instances of Result with HubResult
- [ ] Review network/p2p
- [ ] Review network/sync 
- [ ] Review network/rpc
- [ ] Review storage/engine
- [ ] Review storage/stores
- [ ] Review storage/db
- [ ] Review storage/flatbuffers
- [ ] Review storage/provider
- [ ] Review utils

**Comment by varunsrin** [comment]
This feature has been partially completed and the checklist is slightly out of date. However, many areas of the codebase still need to be upgraded.
