### ISSUE TITLE
No Incoming Connections! Are your ports open?

### ISSUE THREAD

**Issue by Deelux** [farcasterxyz/hub-monorepo#2131]
**What is the bug?**
I don't think it's a bug but I have tried all I could find online all without success. So I'm here asking the community if they have any idea how to fix this challenge:
After installing the bubble app and running the farcaster node, everything is working but the Inbound Sync Attempts.

I have double checked and when I run  "sudo ufw allow 2283/tcp" it says: "Skipping adding existing rule. Skipping adding existing rule (v6)."

Does anyone have any idea how to fix this?

**How can it be reproduced? (optional)**
I'm running a VPS on Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-105-generic x86_64)

Any help is greatly appreciated. 

**Additional context (optional)**

**Comment by sds** [comment]
Hey @Deelux, without more context about the environment you're running it's difficult to help. 

It's important to note that **inbound sync** attempts don't prevent your hub from operating correctly—it just prevents your hub from being able to share data with other hubs on the global network, but it can still find other hubs and get data from them.

A common issue is that Hubble requires **BOTH** ports 2282 and 2283 exposed in order to receive inbound traffic. Just one or the other is not enough.

Exposing via IP tables (like you do in `sudo ufw allow 2283/tcp`) may not be enough. You need to make sure that the VPS itself allows traffic from the public internet to ports 2282 and 2283 (cloud providers refer to this concept as security groups, ingress rules, etc.)

I'm going to close this issue for now. There are other issues you can consult, e.g.
- https://github.com/farcasterxyz/hub-monorepo/issues/2041
- https://github.com/farcasterxyz/hub-monorepo/issues/2061

For context on why this warning was introduced in the first place:
- https://github.com/farcasterxyz/hub-monorepo/issues/1157
