### ISSUE TITLE
bug (hubble): Sync 99%

### ISSUE THREAD

**Issue by roryhuynh** [farcasterxyz/hub-monorepo#2138]
I did restart service but it 99%
![Screenshot 2024-07-09 103651](https://github.com/farcasterxyz/hub-monorepo/assets/139830758/0f57c881-cdf6-4196-bf6b-9b24a5515492)

**Comment by sds** [comment]
Hey @roryhuynh, this is expected. It is almost impossible to be 100% synced—the network is distributed and new messages are constantly being created. There are almost always some messages in flight that one hub has which another hub doesn't. 

Perhaps we could change this number to include some decimal places to make this more clear, but going to close for now as this is expected behavior.
