### ISSUE TITLE
Node doesnt see gossip ports

### ISSUE THREAD

**Issue by ImDdae** [farcasterxyz/hub-monorepo#2306]
Hello, i've tried multiple times to solve this problem but nothing seems to work, i've checked thousands of times that my ports are open, i've edited .env file like https://docs.farcaster.xyz/hubble/troubleshooting told me to, but nothing seems to work

**Additional context (optional)**
My vps is on Ubuntu 22.04
and also i repeat i've checked thousands of times, the ports are open
![Screenshot 2024-09-11 153851](https://github.com/user-attachments/assets/9ec2f9a9-3818-4dc3-b793-845e770bef96)
![Screenshot 2024-09-11 153904](https://github.com/user-attachments/assets/a3f30d8d-d1c2-4669-989b-5ebd72b2ef35)

**Comment by AX1S99** [comment]
same here

**Comment by justintanner** [comment]
![Terminal - collection_pub — -bash — 138×52 2024-09-28 at 8 27 41 PM](https://github.com/user-attachments/assets/1381513f-9a43-4161-aaa0-ea8e2709ce11)

I'm having the same issue setup is:

- VPS on Contabo
- Ubuntu 22.04.5 LTS
- Installed via script
- Set firewall settings (see screenshot above)
- RPC URL from Infura also tried Alchemy (see .env vars below.

Please advise.

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/66c9f059-232d-47ec-a73c-bc3cbd8150ce)

**Comment by sds** [comment]
Hey there, sorry for the delay in response.

While we cannot confirm, we believe some cloud providers were (at least partially) blocking traffic on Farcaster-related ports for some time due to the large number of people running a hub. Even if your server's local firewall allows access, the provider you're running the VPS on can still block traffic to ports.

We recommend using [Neynar](https://neynar.com/) rather than running your own hub going forward. Generally, we cannot assist with these kinds of network issues.
