### ISSUE TITLE
bug (hubble): Hub out of sync

### ISSUE THREAD

**Issue by flyingrabbit-lab** [farcasterxyz/hub-monorepo#2332]
**What is the bug?**
My hub has missing messages although grafana shows 100% synced.
I have tried everything on the troubleshooting page.
Random messages (cast, reactions) are missing.

This is my grafana dashboard:
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/9e0c2e18-52da-438b-b48b-447c3a72c234">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/2247700b-b9ae-43c1-b27d-ffc7431a28de">
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/1f092c5d-b732-4396-837d-dacdbdda991c">
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/fe42f579-9c1d-4b6a-b889-962dd0ed5d08">

Reseting the db works, but then after some time it has missing messages again.

**Comment by AX1S99** [comment]
i think it is because of logs. the node stores 2 gp logs. so when it is showing 100%, may be it is considering the success logs

**Comment by flyingrabbit-lab** [comment]
> i think it is because of logs. the node stores 2 gp logs. so when it is showing 100%, may be it is considering the success logs

What can I do about it, to not be out os sync?

**Comment by Z3R013x** [comment]
Exactly same bug on my side too... it was working just fine, few days ago I had to reinstall OS on server, after installing node via script that runs it via docker, this annoying bug occurs, tried resetting DB, pruning docker & all volumes and install node again, reinstalled OS again, nothing works :/

**Comment by alexchenzl** [comment]
> Exactly same bug on my side too... it was working just fine, few days ago I had to reinstall OS on server, after installing node via script that runs it via docker, this annoying bug occurs, tried resetting DB, pruning docker & all volumes and install node again, reinstalled OS again, nothing works :/ even on fresh install I get 1-2 peers, after some time I get 0 peers and no gossips.

Same issue happens on my server.

**Comment by sds** [comment]
Could you share some example error messages?

In the original screenshot for this issue (the middle of the Grafana dashboard) it shows there were no inbound gossip connections. You can't discover peers if they can't communicate with you.

This is likely an error with your local or cloud provider networking, as we are not seeing any issues with our production hubs.

Also, please make sure you are running the latest hub version.

**Comment by sds** [comment]
If the peers can't connect to you they can't sync. Incoming gossip not working (Grafana dashboard error above) indicates that your hub is not reachable on the public internet, likely because it's behind a NAT gateway.

We highly recommend avoiding running a hub yourself and using a provider (such as [Neynar](https://neynar.com/)) to expose a hub API for you.

I'm going to close this, but if you have more information that changes the story, let's open a new ticket and discuss there. Thank you!

**Comment by Z3R013x** [comment]
TCP ports required for server is reachable, can see open ports externally without any issue

@sds

**Comment by sds** [comment]
I just redeployed our production hubs. We're not seeing this issue. There must be something specific about the way you're running your hubs.

Remember, both ports 2282 and 2283 need to be reachable from the public internet. It's possible your provider might be blocking traffic, or something else unexpected and outsider of Hubble is occurring.

If you'd like to receive more support on this, open a new ticket and:
- Provide clear error logs demonstrating the problem
- Provide proof that your hub is reachable externally (you can send me an IP address via direct cast on Warpcast if you like so I can independently verify it's open)
- Include the configuration you are using. Are you using the `hubble.sh` script? Which OS are you using?

We **strongly** suggest running hubs using a provider like Neynar for just this reason. Hubs are sometimes challenging to run, and given our current efforts to migrate to Snapchain we likely aren't going to be making much investment on the current hub implementation until after that migration is complete, since it solves many known problems (mostly performance-related) with sync.

I'm going to lock this thread. Thank you for your understanding.
