### ISSUE TITLE
bug (hubble): Inbound Gossip Connections

### ISSUE THREAD

**Issue by ashkazen** [farcasterxyz/hub-monorepo#2364]
The "Inbound Gossip Connections" parameter is highlighted in red, showing no peer count. According to the tooltip, "Peers with open inbound connections. Requires port 2282 to be open. Gossip works even without inbound connections, but not having any may affect your peer score and network health." However, we have confirmed that traffic to port 2282 is indeed open and functioning. Additionally, the line BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282 has been added to the .env file to ensure proper configuration.

![2282](https://github.com/user-attachments/assets/64397f4e-3239-4a05-bef0-f015760a4cb6)

**Comment by sds** [comment]
There are multiple issues like this that have been reported, all closed with the same answer: this is likely a configuration error with your network. If you don't expose your gossip port to the public internet, you won't get inbound connections.

If you don't understand what that means, we strongly suggest you use a provider like [Neynar](https://neynar.com/) instead of running your own hub. Thank you.
