### ISSUE TITLE
bug (hubble): Issue in Peers

### ISSUE THREAD

**Issue by iiamscarface** [farcasterxyz/hub-monorepo#2375]
Hi Team,

I have bootstrapped the hub with a non-default peer by adding the following line to your .env file: BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282

After this 1 peer showed up for like an hour but later it again started showing Zero.

Is that an issue or not?

Please refer screenshot attached.
![Farcaster Peer Issue](https://github.com/user-attachments/assets/8a3c7469-751c-4b69-be9e-7b0653fc0563)

**Comment by sds** [comment]
In the middle of your screen you can see that you have no **inbound** connections. This is a network configuration on your side—other hubs can't communicate with you, you can only communicate with them (via **outbound** connections).

We highly recommend using a provider like [Neynar](https://neynar.com/) instead of running your own hub. In general, we won't assist with network configuration issues as they are not in our control.
