### ISSUE TITLE
bug: re-signing signers won't allow the new messages to be accepted correctly

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#577]

**Comment by pfletcherhill** [comment]
Right now when a signer is removed, we add a `RevokeSignerJobPayload` to the `RevokeSignerJobQueue`. Then after an hour, the job is processed, and the `revokeMessagesBySigner` engine method is called, which deletes all the messages signed by that signer.

During that hour, if a client tries to resign messages originally signed by that signer, their new messages will be rejected with duplicate message errors (i.e. the hub already has a message with that hash). However, we want hubs to merge the new messages, so they're not revoked after the hour when the revoke signer job is processed.

One option would be to check the revoke signer queue when we encounter a duplicate message error to see if the signer of the existing message has been removed. The downside of this approach is that stores currently just use tsHashes of messages to identify and resolve conflicts, and we'll need two extra db queries per merge to check the signer—one to get the full message of the duplicate in order to get the signer and a second to check if that signer is still active.

An alternate approach would be to enqueue the messages that will be revoked when the signer is removed (instead of the signer). Then when we check for conflicts, we can add just one additional query when we encounter a duplicate to check if the tsHash in question is queued to be revoked. If so, we can merge the new message and remove the tsHash from the revoke queue in the same transaction.

The downside of this approach is that it is more storage intensive. We will end up storing two entries for every message queued for revocation—one to order the queue so we revoke messages after an hour and in order, and a second to index the queue for easy tsHash lookups. The storage requirements are temporary though, as the revoke queue is continuously worked off.

My preference is for the second approach to keep merges as fast as possible.

**Comment by adityapk00** [comment]
I think option 2 makes sense, especially since the extra storage is only for the duration of the of the hour that the signer is revoked. And since signer revokes are somewhat rare, it should be fine. Option 1 adds a new lookup for every new message, which seems expensive.

**Comment by varunsrin** [comment]
This issue still exists with the move to onchain signers.

**Comment by sanjayprabhu** [comment]
Why does this still exist? Once we revoke an onchain signer, we cannot add it back again.

**Comment by sds** [comment]
Closing since I don't think the original spirit of this issue is a problem anymore, since we're no longer signing signers using protocol messages, but are instead managing signers onchain.
