### ISSUE TITLE
docs: encourage usage of waitForReady pattern

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#765]
The documentation encourages users to just call `getSSLHubRpcClient` and move forward with calling it. We should instead encourage people to follow the gRPC pattern of checking if the connection has been established and erroring out otherwise.

Roughly, something like this: 

```typescript
const client = getInsecureHubRpcClient('testnet1.farcaster.xyz:2283');
client.$.waitForReady(Date.now() + 5000, (e) => {
    if (e) { console.log(e); } else { console.log("Client connection established"); } 
});
```

**Comment by vinliao** [comment]
@varunsrin I made this branch that solves this Issue: https://github.com/vinliao/hubble/blob/docs-patch-2/packages/hub-nodejs/docs/Client.md. Haven't turned it into a PR yet because it's assigned to you (I don't know if you're working on it or not, so it feels kinda impolite to just make a PR). Do let me know if this branch is good (and if you have any nits). Will make the PR if it's good.

**Comment by varunsrin** [comment]
no, not actively being worked on PR would be appreciated!
