### ISSUE TITLE
bug(hubble): rocksdb crashes

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#846]
**What is the bug?**
```

@eddy on farcaster reported running into this crash: 

1|hubble  | node: ../deps/rocksdb/rocksdb/db/write_batch.cc:1520: rocksdb::Status rocksdb::MemTableInserter::PutCFImpl(uint32_t, const rocksdb::Slice&, const rocksdb::Slice&, rocksdb::ValueType): Assertion `seq_per_batch_' failed.
```

**How can it be reproduced? (optional)**
Unclear

**Additional context (optional)**

Eddy says that only one instance of the hub is running.

**Comment by sanjayprabhu** [comment]
The db corruption seems to be caused due to pm2 being over-eager on restarts. What was happening here is that the hub is crashing for a different reason (unable to traverse NAT) which causes the initial graceful shutdown. And then the hub goes into a crash loop due to db corruption after pm2's first restart.

I think we should handle and provide a clean error message for the nat traversal error. 

For future reference, passing `--restart-delay 1000` into pm2 fixes the db crash loop and should reveal the underlying error. If we keep seeing this, we can modify our instructions to always start pm2 with this param dive deeper into what's causing the bad interaction with pm2.

**Comment by varunsrin** [comment]
we saw another issue with @davidfurlong's hub and this
