### ISSUE TITLE
getHubRpcClient "Named export 'grpc' not found"  in hub-web

### ISSUE THREAD

**Issue by zachterrell57** [farcasterxyz/hub-monorepo#863]
**What is the bug?**
Getting the following error when trying to run the `hub-web` example:

SyntaxError: Named export 'grpc' not found. The requested module '@improbable-eng/grpc-web' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@improbable-eng/grpc-web';
const { grpc } = pkg;

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/zachterrell/Developer/farcaster/farcaster.network/web/node_modules/@farcaster/hub-web/dist/index.mjs (2640)
ModuleJob._instantiate
node:internal/modules/esm/module_job (128:21)
async ModuleJob.run
node:internal/modules/esm/module_job (194:5)
async ESMLoader.import
node:internal/modules/esm/loader (409:24)
async importModuleDynamicallyWrapper
node:internal/vm/module (437:15)

**How can it be reproduced? (optional)**
Running Next.JS 12.2.4 with Typescript, @farcaster/hub-web": "^0.2.4

```typescript
import { getHubRpcClient } from '@farcaster/hub-web'
const fetchData = async () => {
    const client = getHubRpcClient('https://testnet1.farcaster.xyz:2285')
    const castsResult = await client.getCastsByFid({ fid: 15 })

    castsResult.map((casts) => casts.messages.map((cast) => console.log(cast.data?.castAddBody?.text)))
  }

  fetchData()
```

**Comment by pfletcherhill** [comment]
The issue as I understand it is that `@improbable-eng/grpc-web` is a CommonJS module, but the [generated `rpc.ts` file from ts-proto](https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-web/src/generated/rpc.ts) as well as our [`client.ts` file](https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-web/src/client.ts) imports the named export `grpc` from it rather than a default export. This is problematic in some environments, but not all—for instance, you can use the package fine when using Vite. If you have cycles to help, you could try patching the rpc.ts and client.ts files to use the default export, but if that doesn't work we may have to look at using a grpc-web library that uses esm instead.

**Comment by pfletcherhill** [comment]
I'm adding the patch in this PR to see if that helps https://github.com/farcasterxyz/hub-monorepo/pull/867

**Comment by zachterrell57** [comment]
This fixed it! Thanks @pfletcherhill  !
